expose Hints.setUpdateNullField
FinVolution/das pull request #18
Opened 2020-03-31 10:20 UTC by ShengyuanLu

@hejiehui ，有用户需要更新null字段。
将Hints.setUpdateNullField暴露出来即可实现，是否公开此功能？

2020-04-01 10:52 UTC, ShengyuanLu commented
@hejiehui 辉哥，各种sharding的情况都加了单元测试：[Add UpdateNullField unit tests for shardings](https://github.com/ppdaicorp/das/pull/18/commits/c11e81b6009536e05c80dac502b79cf840604860)

2020-04-02 10:05 UTC, hejiehui reviewed
TableDao的UT也要加一下。如果UT与问题，可以看看TableDao的设计文档看看有没有升提示

2020-04-02 10:05 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/Hints.java
> +    public Hints setUpdateNullField() {
方法名就叫updateNullField

2020-04-02 10:45 UTC, ShengyuanLu commented on das-client/src/main/java/com/ppdai/das/client/Hints.java
> +    public Hints setUpdateNullField() {
已改为updateNullField

2020-04-02 10:47 UTC, ShengyuanLu commented
@hejiehui 所有UT都跑通了。加了分库分表和TableDao的UT。

2020-04-02 10:47 UTC, ShengyuanLu commented
> TableDao的UT也要加一下。如果UT与问题，可以看看TableDao的设计文档看看有没有升提示
 所有UT都跑通了。加了分库分表和TableDao的UT。

2020-04-09 09:28 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/Hints.java
> +    Hints set(HintEnum hint, Object value) {
这个方法还是要保持private。不要把HintsEnum暴露给用户接口

2020-04-09 09:29 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/DeletionFieldSupport.java
> +    public String getDeletionColumnName() {
这个方法去掉，对hints的处理要放在deletion support的接口实现里面完成

2020-04-09 09:32 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/LogicDeletionDao.java
> +        if(hints.length == 1 && hints[0] != null) {
这段逻辑放到DeletionFieldSupport.clearDeletionFlag完成

2020-04-09 09:32 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/LogicDeletionSupport.java
> +    String getDeletionColumnName();
这个去掉。不能假定由单个column来完成删除操作，这种做法破坏了抽象层次

2020-04-09 09:37 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/LogicDeletionSupport.java
> +    String getDeletionColumnName();
将原来的void clearDeletionFlag(T entity);改为void clearDeletionFlag(T entity， Hints hints); 其中hints可能为null。

2020-04-09 09:39 UTC, hejiehui reviewed
修改LogicDeletionSupport.clearDeletionFlag，增加Hints参数
将LogicDeletionDao里面对deletionColumn的处理下沉到DeletionFieldSupport

2020-04-09 10:25 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/DeletionFieldSupport.java
> +    public void clearDeletionFlag(T entity, Hints... hints) {
这里不需要Hints...，只需要Hints,注释一下是@Nullable的。因为这个class不是终端用户直接用的，所以没必要做成可变参数

2020-04-09 10:30 UTC, hejiehui commented on das-client/src/main/java/com/ppdai/das/client/LogicDeletionSupport.java
> +    void clearDeletionFlag(T entity, Hints... hints);
这里不需要Hints...，只需要Hints,注释一下是@nullable的。因为这个class不是终端用户直接用的，所以没必要做成可变参数

2020-04-09 10:30 UTC, hejiehui requested changes
这里不需要Hints...，只需要Hints,注释一下是@nullable的。因为这个class不是终端用户直接用的，所以没必要做成可变参数

2020-04-09 11:48 UTC, hejiehui approved these changes

2020-04-09 11:48 UTC, merged